### PR TITLE
ensure `@gradio/client` always returns the correct data

### LINKED ISSUE #8508: Data event return empty data object in JS client
### Describe the bug

Hi,
When executing this specific request with Gradio JS client, the data event is well streamed by the server but not handled by the client, it return empty `data: []`.
This problem occurs both on submit() and predict(). First time I meet this issue by working with Gradio API.
Please note that this is working fine with Python client.
Space used here : https://huggingface.co/spaces/TencentARC/InstantMesh

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Script :
```js
import { Client, handle_file } from "@gradio/client";

async function generate(image_url) {

    const client = await Client.connect("TencentARC/InstantMesh", {
        events: ["status", "data"]
    });

    const image = await fetch(image_url);
    const image_blob = await image.blob();

    // This is working fine
    const result_mvs_image = await client.predict("/generate_mvs", [
        handle_file(image_blob),
        50,
        10000,
    ]);

    // This is returning empty data object
    const job = client.submit("/make3d", []);

    for await (const message of job) {
        if (message.type === "status") {
            // ....    
        }
        if (message.type === "data") {
            console.log(JSON.stringify(message));
        }
    }
}
```

Console output :
```
{"type":"data","time":"2024-06-08XXX:XX:XX.XXXX","data":[],"endpoint":"/make3d","fn_index":4}
```
Event stream :
```
data: {"msg":"estimation","event_id":"XXXXX","rank":0,"queue_size":1,"rank_eta":8.784696620431813}

data: {"msg":"process_starts","event_id":"XXXXX","eta":8.784696620431813}

data: {"msg":"process_completed","event_id":"XXXXX","output":{"data":[{"path":"/tmp/gradio/XXXXX/tmpxxxxxxx.obj","url":"https://tencentarc-instantmesh.hf.space/file=/tmp/gradio/XXXXX/tmpxxxxxxx.obj","size":null,"orig_name":"tmpxxxxxxx.obj","mime_type":null,"is_stream":false,"meta":{"_type":"gradio.FileData"}},{"path":"/tmp/gradio/XXXXX/tmpxxxxxxx.glb","url":"https://tencentarc-instantmesh.hf.space/file=/tmp/gradio/aecbf3a9451adf4613930cd98b816adf65ccf736/tmpxxxxxxx.glb","size":null,"orig_name":"tmpxxxxxxx.glb","mime_type":null,"is_stream":false,"meta":{"_type":"gradio.FileData"}}],"is_generating":false,"duration":16.25681548057373,"average_duration":8.76559287936679},"success":true}

data: {"msg":"close_stream"}
```

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
Using `https://cdn.jsdelivr.net/npm/@gradio/client@1.1.0/+esm` on basic HTML application.
```

### Severity

Blocking usage of gradio

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Closes #8508.

In `handle_payload` which we use to remove state data which is always null, we handle both inputs (request payload) and outputs (response payload) but we were treating everything as if they were inputs. So if there were no input components but there was data returned, it would be removed.

Can reproduce fix this script:

```js
import { Client, handle_file } from "./dist/index.js";

async function generate(image_url) {
	const client = await Client.connect("TencentARC/InstantMesh", {
		events: ["status", "data"]
	});

	const image = await fetch(image_url);
	const image_blob = await image.blob();

	// This is working fine
	const result_mvs_image = await client.predict("/generate_mvs", [
		handle_file(image_blob),
		50,
		10000
	]);

	console.log(result_mvs_image);

	// This is returning empty data object
	const job = client.submit("/make3d", []);

	for await (const message of job) {
		if (message.type === "data") {
			console.log(message);
		}
	}
}

generate(
	"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png"
);
```

Add it to `client/js` as `test.js`, run `pnpm build` and run `node test.js`.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

File: client/js/src/helpers/data.ts [hunk 1]
```diff
@@ -187,14 +187,15 @@ export function handle_payload(
 
 	let updated_payload: unknown[] = [];
 	let payload_index = 0;
-	for (let i = 0; i < dependency.inputs.length; i++) {
-		const input_id = dependency.inputs[i];
+	const deps = type === "input" ? dependency.inputs : dependency.outputs;
```
Comment (pngwn) [inline client/js/src/helpers/data.ts:190]: We just need to check which dependencies we care about here and set it accordingly, when handling `inputs` we use `dependency.inputs` when handling `outputs` we use `dependency.outputs`.

File: client/js/src/utils/handle_blob.ts [hunk 2]
```diff
@@ -41,7 +41,10 @@ export async function handle_blob(
 				path,
 				file_url,
 				type,
-				name: blob instanceof File ? blob?.name : undefined
+				name:
+					typeof File !== "undefined" && blob instanceof File
+						? blob?.name
+						: undefined
```
Comment (pngwn) [inline client/js/src/utils/handle_blob.ts:47]: I was getting an error about `File` not being defined. This check fixes it.
