### PR TITLE
Video/Audio fixes

### LINKED ISSUE #6202: [Gradio 4] Drag and drop is not working for `gr.Video` and `gr.Audio`
### Describe the bug

It's possible to click the area to upload a video, but drag & drop doesn't seem to work.

https://github.com/gradio-app/gradio/assets/25161192/a117d8f5-dadc-4970-882c-074a04d50625

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```py
import gradio as gr

gr.Interface(fn=lambda x: x, inputs="video", outputs="video").launch()
```

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
gradio==4.0.2
```

### Severity

I can work around it

### LINKED ISSUE #6250: Clearing an uploaded video's value switches the source to camera
### Describe the bug

When you upload the video and clear it, the source automatically changes to webcam.

Use the `gradio/video_component` demo on spaces

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

-

### Screenshot

video_clear

### Logs

_No response_

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.0.2
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.0
fastapi: 0.101.0
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.23.0
huggingface-hub: 0.18.0
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.7.2
numpy: 1.26.0
orjson: 3.9.4
packaging: 22.0
pandas: 1.5.3
pillow: 9.2.0
pydantic: 2.4.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.23.0
huggingface-hub: 0.18.0
packaging: 22.0
requests: 2.28.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

- [x] upload-on-drag for video was not working for me because the mimetype check was off
- [x] upload on drag for audio
- [x] If video is not of the correct mimetype, no error is shown so users have no idea what happened
- [x] If ffmpeg is run on the backend, the file is not accessible. We should always add the temp file to the temp file set of the block.
- [x] clearing value of video switches source to camera

Fixes #6250
Fixes #6202 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

File: js/upload/src/Upload.svelte [hunk 1]
```diff
@@ -80,7 +83,7 @@
 		if (!e.dataTransfer?.files) return;
 
 		const files_to_load = Array.from(e.dataTransfer.files).filter((f) => {
-			if (is_valid_mimetype(filetype, f.type)) {
+			if (filetype?.split(",").some((m) => is_valid_mimetype(m, f.type))) {
```
[the remark this answers is not in the document]
Comment (freddyaboulton) [reply js/upload/src/Upload.svelte:86]: The allowed mime types are `video/mp4,video/*` so uploading a non-mp4 would filter everything out

File: js/app/test/video_component_events.spec.ts [hunk 2]
```diff
@@ -0,0 +1,95 @@
+import { test, expect } from "@gradio/tootils";
```
Comment (freddyaboulton) [inline js/app/test/video_component_events.spec.ts:1]: neeeded to add the .ogg file because chromium can't play the mp4 file with h264 codec cause its proprietary. Took me forever to figure out why the play event wasn't triggering 😅

File: js/app/test/video_component_events.spec.ts [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+import { readFileSync } from "fs";
+
+const dragAndDropFile = async (
```
Comment (pngwn) [inline js/app/test/video_component_events.spec.ts:4]: snake case

File: js/app/test/video_component_events.spec.ts [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+			bufferData: `data:application/octet-stream;base64,${buffer}`,
+			localFileName: fileName,
+			localFileType: fileType
+		}
+	);
+
+	await page.dispatchEvent(selector, "drop", { dataTransfer });
+};
+
+test("test video click-to-upload and play-pause trigger", async ({ page }) => {
```
Comment (pngwn) [inline js/app/test/video_component_events.spec.ts:33]: Describe the expected outcome in descriptions.

File: js/app/test/video_component_events.spec.ts [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+	await expect(page.getByLabel("# Change Events")).toHaveValue("3");
+	await expect(page.getByLabel("# Upload Events")).toHaveValue("2");
+
+	await page.getByLabel("play-pause-replay-button").first().click();
+	await page.getByLabel("play-pause-replay-button").first().click();
+	await expect(page.getByLabel("# Play Events")).toHaveValue("2");
+	await expect(page.getByLabel("# Pause Events")).toHaveValue("2");
+});
+
+test("test video drag-and-drop", async ({ page }) => {
```
Comment (pngwn) [inline js/app/test/video_component_events.spec.ts:71]: Same here.

File: js/app/test/video_component_events.spec.ts [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+		"./test/files/file_test.ogg",
+		"file_test.ogg",
+		"video/*"
+	);
+	await page.waitForResponse("**/upload");
+	await expect(page.getByLabel("# Change Events")).toHaveValue("1");
+	await expect(page.getByLabel("# Upload Events")).toHaveValue("1");
+});
+
+test("test video drag-and-drop invalid mime type raises warning toast", async ({
```
Comment (pngwn) [inline js/app/test/video_component_events.spec.ts:84]: Could you rewrite this so it reads more clearly? We don't need the word `test` in the description of a test function that is inside a test file.

File: js/upload/src/Upload.svelte (hunk 1 above)
[the remark this answers is not in the document]
Comment (pngwn) [reply js/upload/src/Upload.svelte:81]: Ah, this was me. I didn't account for a list of mime types.

**Review by pngwn — COMMENTED** [review]
Looks good apart from one or two comments.

File: js/audio/interactive/InteractiveAudio.svelte [hunk 7]
```diff
@@ -220,12 +220,12 @@
 			/>
 		{/if}
 	{:else if active_source === "upload"}
-		<ModifyUpload {i18n} on:clear={clear} absolute={true} />
```
Comment (freddyaboulton) [inline js/audio/interactive/InteractiveAudio.svelte:223]: We should not display the clear button if the value is null.

File: js/app/test/video_component_events.spec.ts (hunk 4 above)
Comment (freddyaboulton) [reply js/app/test/video_component_events.spec.ts]: Done! Also renamed `dragAndDropFile` to `drag_and_drop_file` and moved it to `tooltils` so we can use in multiple test files!

File: js/app/test/video_component_events.spec.ts (hunk 6 above)
Comment (freddyaboulton) [reply js/app/test/video_component_events.spec.ts]: Done!

**Review by pngwn — APPROVED** [review]
Works great! Thanks @freddyaboulton!
