### PR TITLE
chatbot component tweaks

### LINKED ISSUE #8544: chatbot components
### Describe the bug

- if you make the screen small, you can't see the plots properly
- the gallery has a gap at the bottom
- you can't select a different gallery image, it just full screens everything
- the thumb up/ down buttons overlap some of the components
- the autoscrolling sometimes doesn't work

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
asd
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes #8544 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

File: js/chatbot/shared/ButtonPanel.svelte [hunk 1]
```diff
@@ -0,0 +1,116 @@
+<script lang="ts">
+	import LikeDislike from "./LikeDislike.svelte";
+	import Copy from "./Copy.svelte";
+	import type { FileData } from "@gradio/client";
+	import { IconButton } from "@gradio/atoms";
+	import DownloadIcon from "./Download.svelte";
+	import { DownloadLink } from "@gradio/wasm/svelte";
+	// import DownloadIcon from "./DownloadIcon.svelte";
```
Comment (pngwn) [inline js/chatbot/shared/ButtonPanel.svelte:8]: remove

File: js/chatbot/shared/ChatBot.svelte [hunk 2]
```diff
@@ -525,23 +481,30 @@
...
 	.message-row {
 		display: flex;
-		flex-direction: row;
+		flex-direction: column;
 		position: relative;
 	}
 
 	.message-row.panel.user-row {
-		background: var(--color-accent-soft);
+		/* background: var(--color-accent-soft); */
```
Comment (pngwn) [inline js/chatbot/shared/ChatBot.svelte:489]: remove

File: js/chatbot/shared/ChatBot.svelte [hunk 3]
```diff
@@ -554,9 +517,14 @@
 			align-self: flex-start;
 		}
 		.message {
-			width: auto;
+			width: 100%;
+		}
+
+		.panel-full-width {
+			/* padding: calc(var(--spacing-xxl) * 2); */
```
Comment (pngwn) [inline js/chatbot/shared/ChatBot.svelte:524]: remiove

File: js/chatbot/shared/LikeDislike.svelte [hunk 4]
```diff
@@ -1,46 +1,90 @@
...
+	class:selected={selected === "like"}
 >
-	<Dislike selected={selected === "dislike"} />
+	<span>
+		{#if selected === "like"}
+			<ThumbUpActive />
+		{:else}
+			<ThumbUpDefault />
+		{/if}
+		<!-- <ThumbUpDefault /> -->
```
Comment (pngwn) [inline js/chatbot/shared/LikeDislike.svelte:51]: remove

File: js/chatbot/shared/LikeDislike.svelte [hunk 5]
```diff
@@ -1,46 +1,90 @@
...
-		right: 0;
 		cursor: pointer;
 		color: var(--body-text-color-subdued);
-		width: 17px;
-		height: 17px;
-		margin-right: 5px;
+		display: flex;
+		align-items: center;
+		justify-content: center;
+		/* transform: translateX(-10px); */
```
Comment (pngwn) [inline js/chatbot/shared/LikeDislike.svelte:62]: remove

File: js/chatbot/shared/LikeDislike.svelte [hunk 6]
```diff
@@ -1,46 +1,90 @@
...
+		margin-right: 7px !important;
+	}
+
+	span {
+		display: inline-block;
+		/* width: 15px;
+		height: 15px; */
```
Comment (pngwn) [inline js/chatbot/shared/LikeDislike.svelte:69]: remove

File: js/chatbot/shared/LikeDislike.svelte [hunk 7]
```diff
@@ -1,46 +1,90 @@
...
+	.selected:hover {
+		color: var(--color-accent);
+	}
+
+	.like-button {
+		transform: translateY(0px);
+	}
+
+	.dislike-button {
+		/* transform: translateY(1px); */
```
Comment (pngwn) [inline js/chatbot/shared/LikeDislike.svelte:88]: rem,ove

File: js/plot/shared/plot_types/PlotlyPlot.svelte [hunk 8]
```diff
@@ -22,13 +22,21 @@
...
 		load_plotly_css();
+		await tick();
 		let plotObj = JSON.parse(plot);
+
+		// the docs aren't very good but this works
+		plotObj.config = plotObj.config || {};
+		plotObj.config.responsive = true;
+		plotObj.responsive = true;
+		plotObj.layout.autosize = true;
+
```
Comment (pngwn) [inline js/plot/shared/plot_types/PlotlyPlot.svelte:35]: this doesn't work apparently, investigating.

Comment (pngwn) [reply js/plot/shared/plot_types/PlotlyPlot.svelte:35]: copilot knew. fixed now.

File: gradio/utils.py [hunk 9]
```diff
@@ -265,6 +265,9 @@ def iter_py_files() -> Iterator[Path]:
                 if changed.suffix == ".py":
                     changed_in_copy = _remove_no_reload_codeblocks(str(changed))
                     if changed != reloader.demo_file:
+                        print(
```
Comment (pngwn) [inline gradio/utils.py:268]: remove

File: js/app/test/hello_world.reload.spec.ts [hunk 10]
```diff
@@ -26,6 +26,8 @@ if __name__ == "__main__":
 			PYTHONUNBUFFERED: "true"
 		}
 	});
+
```
Comment (pngwn) [inline js/app/test/hello_world.reload.spec.ts:29]: remove

File: js/wasm/svelte/file-url.ts [hunk 11]
```diff
@@ -22,12 +23,22 @@ export function should_proxy_wasm_src(src: MediaSrc): boolean {
...
 
-	const maybeWorkerProxy = getWorkerProxyContext();
+	if (maybeWorkerProxy == null) {
+		try {
+			maybeWorkerProxy = getWorkerProxyContext();
+		} catch (e) {
+			// We are not in the Wasm env. Just use the src as is.
+			return src;
+		}
+	}
```
[the remark this answers is not in the document]
Comment (pngwn) [reply js/wasm/svelte/file-url.ts:40]: I was seeing some kind of error when this was called outside of the main app and I wondered if it because something wasn't handled in lite, later I wanted us to not import if we had already imported to speed things up a bit.

File: js/plot/shared/plot_types/PlotlyPlot.svelte [hunk 12]
```diff
@@ -22,14 +24,35 @@
...
+		);
+
+		Plotly.Plots.resize(plot_div);
+
+		plot_div.on("plotly_afterplot", () => {
+			dispatch("load");
+		});
 	});
+
+	onMount(() => {});
```
[the remark this answers is not in the document]
Comment (pngwn) [reply js/plot/shared/plot_types/PlotlyPlot.svelte]: Nyet! Leftover.

**Comment by dawoodkhan82** [comment]
Just catching up on some PRs. Thanks for adding all these fixes @pngwn !
