### PR TITLE
ensure falsey values are set to null for images

### LINKED ISSUE #1838: Image component in a tab cannot be clicked
### Describe the bug

I'm seeing a weird bug where if a `gr.Image` is inside a `gr.Tab` that is not selected by default, then it cannot be clicked to upload an image -- until it is cleared (even though no image is loaded). It's a bit hard to describe, so look at the reproduction below:

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```py
import gradio as gr

demo = gr.Blocks()

with demo:
    with gr.Tabs():
        with gr.TabItem("Flip Text"):
            gr.Textbox()
        with gr.TabItem("Flip Image"):
            image_input = gr.Image()
            image_output = gr.Image()
            image_button = gr.Button("Flip")

    image_button.click(lambda x:x, inputs=image_input, outputs=image_output)

demo.launch()
```

Here, `image_input` should be clickable, but it is not (until you press the X to clear it):

image

### Screenshot

_No response_

### Logs

```shell
N/A
```

### System Info

```shell
3.1
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by pngwn**
Closes #1838.

### CODE REVIEW

File: ui/packages/app/src/components/Image/Image.svelte [hunk 1]
```diff
@@ -27,6 +27,8 @@
 
 	$: value, dispatch("change");
 	let dragging: boolean;
+
+	$: value = !value ? null : value;
```
Comment (aliabid94) [inline ui/packages/app/src/components/Image/Image.svelte:31]: how about `value = value || null`?

**Review by aliabid94 — APPROVED** [review]
lgtm
