### PR TITLE
Fix infinite requests when doing tab item select

### LINKED ISSUE #2069: Infinite api requests when updating a component inside a tab on tab select
### Describe the bug

When updating the value of a component with the `TabItem.select` event, the front-end makes infinite requests to the backend and gets stuck.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

In the following demo, note it get stuck if you switch tabs:

```python
import gradio as gr
    
tab_names = ["one", "two"]

with gr.Blocks() as demo:

    with gr.Tabs():
        for name in tab_names:
            with gr.TabItem(name) as rl_tab:
                num = gr.Number()
                rl_tab.select(lambda: 3, inputs=[], outputs=[num])

demo.launch()
```

### Screenshot

infinite_requests

### Logs

```shell
Nothing logged from the backend
```

### System Info

```shell
Gradio 3.1.7 and main
MacOSX
Chrome
```

### Severity

blocking upgrade to latest gradio version

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description
Fixes #2069 

To test, run the reproducer and switch tabs successfuly. `blocks_plug` also works as expected.

```python
import gradio as gr
    
tab_names = ["one", "two"]

with gr.Blocks() as demo:

    with gr.Tabs():
        for name in tab_names:
            with gr.TabItem(name) as rl_tab:
                num = gr.Number()
                rl_tab.select(lambda: 3, inputs=[], outputs=[num])

demo.launch()
```

Don't think this breaks anything but would be good to get the opinion of a front-end expert.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: ui/packages/tabs/src/Tabs.svelte [hunk 1]
```diff
@@ -56,7 +56,7 @@
 			{:else}
 				<button
 					class="px-4 pb-2 pt-1.5 border-transparent text-gray-400 hover:text-gray-700 -mb-[2px] border-2 border-b-0"
-					on:click={() => (selected = t.id)}
+					on:click={() => change_tab(t.id)}
```
Comment (freddyaboulton) [inline ui/packages/tabs/src/Tabs.svelte:59]: TBH not sure how the old code was causing the original problem but it seems to be fixed now 😬

**Comment by abidlabs** [comment]
Can confirm that the demos work, but it would be good to get some confirmation from the front end team: @aliabid94 @dawoodkhan82 @pngwn?
