### PR TITLE
fix: add ARIA landmarks for accessibility

### LINKED ISSUE #5771: Add Landmarks For Accessibility
- [✅] I have searched to see if a similar issue already exists.

**Webpage Navigation**  

Accessibility tools use landmarks as markers for navigation. 

**CSS Code / Markers or Equivalent**  

For every block, a landmark element by default.

**Additional context**  

- [W3C Landmarks](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation.html)
- [Huggingface Discussion](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/263#651aed757d45b917399ec8ec)

### PR DESCRIPTION
**Pull request by majiayu000**
## Summary
- Add `role="main"` to main content container using semantic `<main>` element
- Add `role="group"` with `aria-label` support to Block component for fieldsets
- Add `role="group"` with `aria-label` to BaseForm component
- Add `role="dialog"` and `aria-modal` to API docs and settings modals
- Add `aria-label` to footer navigation

## Test plan
- [x] Added unit tests for Block component accessibility attributes
- [x] Added unit tests for BaseForm component accessibility attributes
- [x] All existing tests pass

Fixes #5771

Signed-off-by: majiayu000 <1835304752@qq.com>

### CODE REVIEW

**Comment by freddyaboulton** [comment]
hi @majiayu000 ! Some of the playwright tests are failing in this PR.

@hannahblair can you review?

**Comment by freddyaboulton** [comment]
Hi @majiayu000 ! Thanks for following up with this pr. Looks like one playwright test is failing now and it's because there are two <main> elements now when creating a multipage Gradio app.

File: js/atoms/src/Block.svelte [hunk 1]
```diff
@@ -129,6 +130,8 @@
 		style:border-width="var(--block-border-width)"
 		class:auto-margin={scale === null}
 		dir={rtl ? "rtl" : "ltr"}
+		role={type === "fieldset" ? "group" : undefined}
+		aria-label={label}
```
Comment (hannahblair) [inline js/atoms/src/Block.svelte]: i think this role is redundant, `fieldset` is implicit if its a `<group>`

File: js/atoms/src/Block.svelte [hunk 2]
```diff
@@ -129,6 +130,8 @@
 		style:border-width="var(--block-border-width)"
 		class:auto-margin={scale === null}
 		dir={rtl ? "rtl" : "ltr"}
+		role={type === "fieldset" ? "group" : undefined}
```
Comment (hannahblair) [inline js/atoms/src/Block.svelte]: i think this role is redundant, fieldset is implicit if it's a group

**Comment by hannahblair** [comment]
i think this is good to merge, just a nit above. thanks for contributing and being patient with this one @majiayu000!

**Comment by majiayu000** [comment]
Fixed! I removed the redundant role attribute as suggested.

**Comment by hannahblair** [comment]
i'm fairly sure the last failing test isn't related so will merge this
