### PR TITLE
Fix ColorPicker not firing focus, blur, or submit events

### LINKED ISSUE #12854: ColorPicker does not fire focus, blur, or submit events
### **Description**

The `ColorPicker` component does not trigger `focus`, `blur`, or `submit` events as expected.

I verified this behavior in multiple versions, and the issue is consistent.
Only the `change` and `input` events are firing correctly.

This makes it difficult to handle validation, UI state changes, and form workflows that rely on focus management or submit handling.

---

### **Versions Tested**

* 5.49.1
* 6.0.1
* 6.1.0
* 6.2.0
* 6.3.0
* 6.4.0
* 6.5.1

Both versions show the same behavior.

---

### **Actual Behavior**

* ❌ `focus` does not fire
* ❌ `blur` does not fire
* ❌ `submit` does not fire
* ✅ `change` works
* ✅ `input` works

---

(Written with the help of ChatGPT)

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    CP = gr.ColorPicker(label='Color Picker')


    CP.focus(fn=lambda : gr.Info('focus'))
    CP.blur(fn=lambda : gr.Info('blur'))
    CP.submit(fn=lambda : gr.Info('submit'))

demo.launch()
```

### Screenshot

_No response_

### Logs

```shell

```

### System Info

```shell
6.5.1 is the same.


Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 6.3.0
gradio_client version: 2.0.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 24.1.0
anyio: 4.9.0
audioop-lts is not installed.
brotli: 1.1.0
fastapi: 0.115.12
ffmpy: 0.6.0
gradio-client: 2.0.3
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 1.2.3
jinja2: 3.1.6
markupsafe: 3.0.2
numpy: 2.2.6
orjson: 3.10.18
packaging: 25.0
pandas: 2.3.0
pillow: 11.2.1
pydantic: 2.11.5
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
safehttpx: 0.1.7
semantic-version: 2.10.0
starlette: 0.46.2
tomlkit: 0.13.3
typer: 0.16.0
typing-extensions: 4.14.0
uvicorn: 0.34.3
mcp is not installed.
pydantic: 2.11.5
authlib is not installed.
itsdangerous is not installed.


gradio_client dependencies in your environment:

fsspec: 2025.5.1
httpx: 0.28.1
huggingface-hub: 1.2.3
packaging: 25.0
typing-extensions: 4.14.0
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by veeceey**
## Description

Fixes #12854 - ColorPicker component did not trigger `focus`, `blur`, or `submit` events because it used Svelte 4 legacy `on:` event directives in a Svelte 5 runes-mode component.

Migrated to Svelte 5 native event handlers and wrapped the component in a `<div>` using `focusin`/`focusout` to track focus across all interactive elements. Submit event correctly fires on Enter key in the color text input.

Closes: #12854

## AI Disclosure

- [x] I used AI to help author and review this PR (Claude Code)

## Testing and Formatting Your Code

1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash scripts/run_backend_tests.sh`

2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by veeceey** [comment]
## Manual Verification

Tested the ColorPicker event migration fix that enables `focus`, `blur`, and `submit` events.

### Test Setup
```python
import gradio as gr

with gr.Blocks() as demo:
    color = gr.ColorPicker(label="Test Color", value="#FF0000")
    output = gr.Textbox(label="Event Log")
    
    color.focus(lambda: "Focus event fired", outputs=output)
    color.blur(lambda: "Blur event fired", outputs=output)
    color.submit(lambda x: f"Submit event fired with {x}", inputs=color, outputs=output)
    color.change(lambda x: f"Change event fired with {x}", inputs=color, outputs=output)

demo.launch()
```

### Results
✅ **Focus event fires** - Clicking the color swatch button triggers the focus event  
✅ **Blur event fires** - Clicking outside the ColorPicker triggers the blur event  
✅ **Submit event fires** - Typing a color value and pressing Enter triggers the submit event  
✅ **Change event still works** - Selecting a color still triggers the change event correctly  
✅ **Input event still works** - Typing in the color text input still triggers input events  
✅ **Composite focus tracking** - Moving focus between the button and dialog input doesn't incorrectly fire blur/focus events

The migration from Svelte 4 legacy `on:` directives to Svelte 5 native event handlers (`onfocusin`, `onfocusout`, etc.) successfully enables all event types. The wrapper element with `focusin`/`focusout` properly tracks focus across all interactive elements.

**Comment by veeceey** [comment]
All checks passing ✓ Mergeable: YES | Comprehensive manual testing evidence provided in PR description. Ready for @gradio maintainers review and merge.

**Comment by veeceey** [comment]
Hi @gradio maintainers — friendly ping on this PR. It migrates ColorPicker events (focus, blur, submit) to work properly. All checks are passing and manual test results are provided. Would appreciate a review when you have a moment. Thank you!

**Comment by veeceey** [comment]
@freddyaboulton Thanks for the review! You're right, that was way more than needed. I've simplified it — now it just adds `onfocus={on_focus}` and `onblur={on_blur}` to the dialog-button and keeps the submit keydown handler on the text input. Much cleaner.

File: js/colorpicker/shared/Colorpicker.svelte [hunk 1]
```diff
@@ -211,6 +211,11 @@
 						on:change={(e) => {
```
Comment (freddyaboulton) [inline js/colorpicker/shared/Colorpicker.svelte]: This looks good! But just a note that svelte 5 does not let you mix `on:change` (with a colon) and `onfocus` (no colon). Please change them to be without a colon!

**Comment by veeceey** [comment]
Fixed the CI failure - Svelte 5 doesn't allow mixing old `on:click` with new `onclick` syntax on the same element. Converted `on:click` to `onclick` on the dialog-button and `on:change` to `onchange` on the text input (both elements had new-syntax handlers alongside old-syntax ones).

**Comment by freddyaboulton** [comment]
There are some other places that need to be fixed @veeceey !

**Comment by veeceey** [comment]
@freddyaboulton Good catch, sorry about that\! I've converted all the remaining old-style `on:` handlers to Svelte 5 syntax — `on:mousedown` -> `onmousedown`, `on:mousemove` -> `onmousemove`, `on:mouseup` -> `onmouseup`, and the two `on:click` handlers -> `onclick`. Also ran prettier. Should be clean now.

**Comment by veeceey** [comment]
Thanks for the review and merge @freddyaboulton\! Appreciate the feedback on keeping it simple and catching the remaining old-style handlers.
