### PR TITLE
Image Editor Clear Event

### LINKED ISSUE #11045: ImageEditor 'Clear canvas' button does not trigger associated event listener in Gradio 5.24–5.25.2
### Describe the bug

In Gradio versions 5.24 to 5.25.2, clicking the "Clear canvas" button in the ImageEditor component does not call the registered event listener. Instead, it silently reinitializes the canvas to the component's default state.

This behavior is inconsistent with the behavior of the previous versions, where clicking the "Clear canvas" button correctly triggers the event listener and allows updating the component with EditorValue object.

The reproducer below adds a simple event listener that sets EditorValue object and prints a message to the console.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import numpy as np
from gradio.components.image_editor import EditorValue


def process_image(image: EditorValue):
    return image["layers"][0].sum() if image["layers"] else 0


def default_image() -> EditorValue:
    size = 512
    img = np.zeros((size, size, 3), np.uint8)
    mask = np.zeros((size, size, 4), np.uint8)
    return EditorValue(
        background=img,
        layers=[mask],
        composite=None,
    )


with gr.Blocks() as demo:
    image_editor = gr.ImageEditor(
        value=default_image(),
    )

    text = gr.Textbox(
        value=process_image,
        inputs=[image_editor],
    )

    @image_editor.clear(outputs=[image_editor])
    def on_clear() -> EditorValue:
        print("on_clear")
        return default_image()


demo.launch()

```

### Screenshot

Example of the **incorrect** behavior:

After pressing "Clear canvas" button in gradio-5.25.2, the event listener is not called at all, and image editor gets reinitialized to default values of the component:

Image

For reference, the **correct** behavior in gradio-5.23.0:
After pressing "Clear canvas" button, the event listener properly re-initializes ImageEditor:

Image

### Logs

```shell

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.25.2
gradio_client version: 1.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.7.0
audioop-lts is not installed.
fastapi: 0.115.6
ffmpy: 0.5.0
gradio-client==1.8.0 is not installed.
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 0.29.1
jinja2: 3.1.5
markupsafe: 2.1.5
numpy: 1.26.4
orjson: 3.10.13
packaging: 24.1
pandas: 2.2.3
pillow: 11.1.0
pydantic: 2.10.5
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.9.9
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.41.3
tomlkit: 0.13.2
typer: 0.15.1
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.34.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.12.0
httpx: 0.28.1
huggingface-hub: 0.29.1
packaging: 24.1
typing-extensions: 4.12.2
websockets: 14.1
```

### Severity

Blocking usage of gradio

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes #11045

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Testing and Formatting Your Code

1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash scripts/run_backend_tests.sh`

2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) `bash scripts/format_frontend.sh`

### CODE REVIEW

File: js/imageeditor/shared/ImageEditor.svelte [hunk 1]
```diff
@@ -605,6 +605,7 @@
 				on:set_zoom={(e) => handle_zoom_change(e.detail)}
 				on:zoom_in={() => zoom_in_out("in")}
 				on:zoom_out={() => zoom_in_out("out")}
+				on:clear={() => dispatch("clear")}
```
Comment (pngwn) [inline js/imageeditor/shared/ImageEditor.svelte:608]: I think we can just dispatch clear in the `remove_image` event handler without adding the other clear event to the Controls component.

**Review by abidlabs — APPROVED** [review]
confirmed that the issue is resolved! (edit: just saw @pngwn's comment)
