### PR TITLE
Revert chatbot styling

### LINKED ISSUE #8666: Chatbot AI message borders have disappeared as well as Like boxes
### Describe the bug

Thanks for the great work on gradio.

There seem to be a problem with gradio 4.37

Even if you go to the theme demo page, you can see that chatbot ai message borders have disappeared 

https://www.gradio.app/guides/theming-guide

image

There is also a problem with the likes and copy buttons : 
AI likes + copy button borders are not visible
human message copy button are not visible at all

Here is an example with the basic base theme : 
image
there should be borders around AI message and the AI message like box, and a like box under human message.

Also, I didn't find if any theme parameters could add the borders and the boxes back. It is very difficult to understand which theme parameters controls what in the chatbot. For instance, border_color_accent_subdued controls the color of human border messages, but where is it documented ? Which parameter to use to control the border color of AI messages ?

By the way, I think that the border of like/copy buttons should be of the same color of the messages they are under (thus different if it is a like/copy button under an AI message, or a copy button under a human message - up to now it seems it was not possible to differentiate).  

Thanks a lot

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://www.gradio.app/guides/theming-guide

you can also use the following ChatBot

gr.Chatbot(
        show_label=False,
        show_copy_button=True,
        bubble_full_width=False,
        likeable=True,
    )

### Screenshot

image

### Logs

_No response_

### System Info

```shell
gradio==4.37.2
```

### Severity

Blocking usage of gradio

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Fixes #8666 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

File: js/chatbot/Index.svelte [hunk 1]
```diff
@@ -124,6 +124,7 @@
 			upload={gradio.client.upload}
 			_fetch={gradio.client.fetch}
 			load_component={gradio.load_component}
+			{msg_format}
```
Comment (freddyaboulton) [inline js/chatbot/Index.svelte:127]: I think needs to be `msg_format={type}` because I renamed to `type`
