### PR TITLE
reload on css changes + fix css specificity

### LINKED ISSUE #6735: Dev mode does not reload custom css
- [x] I have searched to see if a similar issue already exists.

When running dev mode either normally or via the cc dev command, custom csss is not reloaded. You have to restart the server manually.

### LINKED ISSUE #6736: Writing custom css is frustrating
- [x] I have searched to see if a similar issue already exists.

Writing custom css is incredibly frustrating, to the point where I'm not sure how people have the patience to even bother. 

We need to improve this somehow. Have a few ideas that I'll add shortly.

### PR DESCRIPTION
**Pull request by pngwn**
## Description

This has been driving me up the wall all weekend, so here is a fix.

- Ensure the app reloads + css is correctly applied when CSS files in a watch dir are edited. cc @freddyaboulton 
- Ensure CSS is correctly applied when CSS (as a string) changed.
- Make working with custom CSS much simpler (genuine fix for #3851) cc @aliabid94 @abidlabs 

This should work fine now with no need for `!important` modifiers or other CSS hacks:

```python
import gradio as gr

css = """
#custom-md h1 {
  color: hotpink;
}

.custom-md h2 {
  color: orange;
}
"""

with gr.Blocks(css=css) as demo:
  gr.Markdown("# Heading one", elem_id="custom-md")
  gr.Markdown("## Heading two", elem_classes=["custom-md"])

demo.launch()
```

We do this by modifying the selectors passed by a user, prepending them with a series of addition selectors to increase their specificity enough that they override the svelte hashed classes. It's hacky but should be relatively robust.

Closes #6735. Closes #6736.

### CODE REVIEW

File: js/app/src/css.ts [hunk 1]
```diff
@@ -18,3 +18,39 @@ export function mount_css(url: string, target: HTMLElement): Promise<void> {
...
+		if (rule instanceof CSSStyleRule) {
+			const selector = rule.selectorText;
+			if (selector) {
+				const new_selector = selector
+					.split(",")
+					.map((s) => `.gradio-container-${version} .contain ${s.trim()}`)
+					.join(",");
+
+				css_string += rule.cssText.replace(selector, new_selector);
+			}
```
Comment (pngwn) [inline js/app/src/css.ts:49]: Lets leave the existing styles in as well, as they are, in case they are targetting something outside of the gradio app + to avoid breaking changes.

**Comment by pngwn** [comment]
`gradio cc dev` was completely broken on main because of a dependency issues, I've fixed that in this branch too.

**Comment by pngwn** [comment]
Need to merge to check some other issues. Feel free to review and I'll address anything in another PR

File: js/app/src/css.ts [hunk 2]
```diff
@@ -18,3 +18,42 @@ export function mount_css(url: string, target: HTMLElement): Promise<void> {
...
+				const new_selector = selector
+					.split(",")
+					.map(
+						(s) =>
+							`gradio-app .gradio-container.gradio-container-${version} .contain ${s.trim()}`
+					)
+					.join(",");
+
+				css_string += rule.cssText;
+				css_string += rule.cssText.replace(selector, new_selector);
```
Comment (abidlabs) [inline js/app/src/css.ts:51]: Nice. I don't think repeating a css rule should have any (non-performance-related) downsides so this should be good

**Comment by abidlabs** [comment]
Cool, looks great to me @pngwn! Thanks for dogfooding this workflow :)

File: js/app/src/css.ts (hunk 2 above)
Comment (pngwn) [reply js/app/src/css.ts:51]: The number of rules should generally be pretty modest, so I think the performance should be ok.
