### PR TITLE
Fix loading css and api when mounted in subpath

### LINKED ISSUE #3472: UI not displaying correctly
### Describe the bug

The UI displays correctly on the local system. But when I upload it to the server, the UI CSS is not present. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

     NA

### Screenshot

Screenshot 2023-03-15 at 12 23 45 AM

### Logs

```shell
No logs. Only a 404 error.
```

### System Info

```shell
This is hosted on railway.app.
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Fixes #3472 

The problem was that the `root` in the config did not properly point to the full path of the gradio app. Moreover, the `client` was also not pointing to the full path of the gradio app so even if the css was loaded properly, all the predictions would 500 because the route was wrong.

My strategy was to add a `root` to the config that specifies the gradio subpath that then gets loaded by the front end.

Not sure if this is the best solution as we didn't need to do this before. Someone more familiar with the new js client feel free to make an alternate suggestion!

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Deployed not on spaces and seems to be working as well (even with queue enabled)

Opening up for review but feel free to correct the approach!

image

**Comment by aliabid94** [comment]
was just looking into this and then saw you opened a PR :P reviewing now

File: ui/packages/app/src/Index.svelte [hunk 1]
```diff
@@ -208,6 +208,8 @@
 
 	$: config && (eager || $intersecting[_id]) && load_demo();
 
+	$: console.log(config);
```
Comment (aliabid94) [inline ui/packages/app/src/Index.svelte:211]: rm

Comment (freddyaboulton) [reply ui/packages/app/src/Index.svelte]: Done and pushed a fix for the case when the path ends in `/`

File: gradio/routes.py [hunk 2]
```diff
@@ -755,6 +755,7 @@ def read_main():
         # Then run `uvicorn run:app` from the terminal and navigate to http://localhost:8000/gradio.
     """
     blocks.dev_mode = False
+    blocks.root = path[: path.rindex("/")] if path.endswith("/") else path
```
Comment (aliabid94) [inline gradio/routes.py:758]: Could do `blocks.root = path[:-1] if path.endswith("/") else path`, right?

Comment (freddyaboulton) [reply gradio/routes.py:758]: Yes!

**Comment by freddyaboulton** [comment]
@aliabid94 @abidlabs I think I fixed the embedding and now you can test with this document

```html
<script
	type="module"
	src="https://gradio-dev-cdn.s3.amazonaws.com/3.21.0/gradio.js"
></script>

<div>
    <gradio-app space="gradio/native_plots"></gradio-app>
    <gradio-app space="gradio/calculator"></gradio-app>
    <gradio-app space="gradio/video_component"></gradio-app>
</div>
```

I uploaded the cdn assets to `https://gradio-dev-cdn.s3.amazonaws.com/3.21.0/gradio.js`

**Comment by abidlabs** [comment]
LGTM @freddyaboulton can confirm it works for me. 

image

I noticed that the Space name is slightly vertically un-aligned. But this is also the case when using the published 3.21 js cdn so I'll create a separate issue for that:

image

Tested mounting a subpath locally and everything works so I think we're good to merge

**Review by abidlabs — APPROVED** [review]

File: ui/packages/client/src/client.ts [hunk 3]
```diff
@@ -350,12 +352,16 @@ function skip_queue(id: number, config: Config) {
 
 async function resolve_config(endpoint?: string): Promise<Config> {
 	if (window.gradio_config && location.origin !== "http://localhost:9876") {
-		return { ...window.gradio_config, root: endpoint };
+		const path = window.gradio_config.root;
```
Comment (noonowl) [inline ui/packages/client/src/client.ts:355]: Shouldn't this part be changed to `window.location.pathname`? It seems that the current value of the root is being included instead of the path variable, which should contain the path.
