### PR TITLE
fix tab error

### LINKED ISSUE #1327: When nesting `gr.Tabs()` the frontend becomes unresponsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried to create an app with nested `gr.Tabs()` but the frontend becomes unresponsive when clicking the outer tabs. If this is not intended to be supported it's not mentioned in the docs.

### Reproduction

Minimal example to reproduce:

```python
import gradio as gr


demo = gr.Blocks()

with demo:
    with gr.Tabs():
        with gr.TabItem("AAA"):
            with gr.Tabs():
                with gr.TabItem("111"):
                    pass

                with gr.TabItem("222"):
                    pass

        with gr.TabItem("BBB"):
            with gr.Tabs():
                with gr.TabItem("111"):
                    pass

                with gr.TabItem("222"):
                    pass

demo.launch()
```

When clicking the outer "BBB" tab, the ui becomes unresponsive.

### Screenshot

_No response_

### Logs

```shell
Google chrome console

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at :7860/assets/Tabs.f15b0f19.js:1:3039
    at Object.a [as update] (:7860/assets/index.08c1410a.js:4:15004)
    at unregister_tab (:7860/assets/Tabs.f15b0f19.js:1:3015)
    at :7860/assets/index.a6cbe4d7.js:1:1859
    at Ar (:7860/assets/index.08c1410a.js:1:900)
    at Array.forEach (<anonymous>)
    at un (:7860/assets/index.08c1410a.js:1:962)
    at Pn (:7860/assets/index.08c1410a.js:4:5549)
    at Object.d (:7860/assets/index.a6cbe4d7.js:1:4490)
    at Pn (:7860/assets/index.08c1410a.js:4:5589)
```
```


### System Info

```
- gradio version 3.0.2
- Ubuntu 20.04
- Firefox 100.0.1
- Google Chrome 99.0.4844.84 (Official Build) (64-bit)
```


### Severity

blocker

### PR DESCRIPTION
**Pull request by pngwn**
Closes #1327.

### CODE REVIEW

File: ui/packages/workbench/src/routes/tabs.svelte [hunk 1]
```diff
@@ -23,3 +23,29 @@
 		<blockquote>I am a quote</blockquote>
 	</TabItem>
 </Tabs>
+
+<Tabs>
+	<TabItem name="tab 1" on:select={() => console.log("tab 1")}>
```
Comment (aliabid94) [inline ui/packages/workbench/src/routes/tabs.svelte:28]: Remove logs below
