### PR TITLE
fix df bool header

### LINKED ISSUE #12690: Dataframe: Header checkbox on bool column also toggles values in other selected columns; no API to hide it
### Describe the bug

When using gr.Dataframe with a bool column (rendered as checkboxes), Gradio shows a header-level checkbox that enables “toggle all” for the column. Clicking that header checkbox unexpectedly changes values in other selected columns as well, causing unintended bulk edits across the table.

In addition, there is currently no public API to hide or disable this header checkbox.

Solution : Hide the header checkbox via CSS
```
/* Scoped to the specific dataframe via elem_id */
#my_df thead input[type="checkbox"] {
  display: none !important;
}
```

https://github.com/user-attachments/assets/8eac3787-ec40-406f-a45c-2b812d6aaf78

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import pandas as pd

rows = [
        {
            "Theme": "DAB",
            "Question": "Quelles sont les dates importantes",
            "Réponse": "Une réponse beaucoup trop longue juste pour tester l'affiche : Sin autem ad adulescentiam perduxissent, dirimi tamen interdum contentione vel uxoriae condicionis vel commodi alicuius, quod idem adipisci uterque non posset. Quod si qui longius in amicitia provecti essent, tamen saepe labefactari, si in honoris contentionem incidissent.",
            "Validation": True,
            "Commentaire": "",
        },
        {
            "Theme": "Custom",
            "Question": "Y'a t'il une liste de véhicules ?",
            "Réponse": "Une **réponse** beaucoup trop longue juste pour tester \nl'affiche : Sin autem ad adulescentiam perduxissent, dirimi tamen interdum contentione vel uxoriae condicionis vel commodi alicuius, quod idem adipisci uterque non posset. Quod si qui longius in amicitia provecti essent, tamen saepe labefactari, si in honoris contentionem incidissent.",
            "Validation": True,
            "Commentaire": "",
        },
    ]

data = pd.DataFrame(rows)

with gr.Blocks() as demo:
  result_questions_df = gr.Dataframe(
      headers=["Theme", "Question", "Réponse", "Validation", "Commentaire"],
      value=data,
      interactive=True,
      wrap=True,
      column_widths=["7%", "13%", "50%", "10%", "20%"],
      col_count=(5, "fixed"),
      datatype=["str", "str", "markdown", "bool", "str"],
      show_fullscreen_button=True,
      show_copy_button=True,
      show_search=True,
      # elem_id="result-questions-table",
      static_columns=[0, 1, 2],
  )
demo.launch()
```

### Screenshot

_No response_

### Logs

```shell

```

### System Info

```shell
Gradio version: 5.50.0
Browser: Microsoft Edge
OS: Windows 11
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by pngwn**
## Description

During the Dataframe refactor, I missed the checkbox in the header for columns with a datatype of bool. This adds that feature back and also adds a test for #12690.

I also made some small UI tweaks:

- left aligned both the header checkbox and cell checkbox so they look nice
- added an indeterminate state to the checkbox for this isecase
- tweaked the input styles to prevent the text shift slightly when toggling editable mode
- tweaked shadow styles so the selected cell is consistent across header cells + regular cells.

Closes: #12690.

### CODE REVIEW

File: js/dataframe/shared/HeaderCell.svelte [hunk 1]
```diff
@@ -66,6 +78,25 @@
...
+					role="button"
+					tabindex="-1"
+					onclick={(e) => e.stopPropagation()}
+					onmousedown={(e) => e.stopPropagation()}
+					onkeydown={(e) => e.stopPropagation()}
+				>
+					<BaseCheckbox
+						value={select_all_state === "checked"}
+						indeterminate={select_all_state === "indeterminate"}
+						label=""
```
Comment (hannahblair) [inline js/dataframe/shared/HeaderCell.svelte]: do we need a value here?

Comment (pngwn) [reply js/dataframe/shared/HeaderCell.svelte]: "select all" maybe? or `Select all ${header_title}` might be good?

**Review by hannahblair — APPROVED** [review]
nice one, thank you so much @pngwn!

File: js/dataframe/shared/HeaderCell.svelte (hunk 1 above)
Comment (hannahblair) [reply js/dataframe/shared/HeaderCell.svelte]: perfect!
