### PR TITLE
Fix Lite dependencies

### LINKED ISSUE #9721: Error Message Visible in Gradio Documentation
### Describe the bug

Hello! Thank you so much for the great project!

However, I encountered a minor issue while reading through the Gradio documentation. Some sections of the Gradio documentation display an error message directly on the page. Although the text is in white, it can still be highlighted and selected. This issue seems to occur mostly in the "Components" section of the documentation, such as on this page: https://www.gradio.app/docs/gradio/checkboxgroup.

It seems that it is because of the environment: `Requested 'starlette<1.0,>=0.40.0', but starlette==0.37.2 is already installed`

Thank you for looking into this!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Visit https://www.gradio.app/docs/gradio/checkboxgroup

### Screenshot

0b8b319a6d8a0fbce13ba9a040401d2

2018e0c731f6dc7517a8a15eb08748d

### Logs

```
PythonError: Traceback (most recent call last):
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 68, in add_requirement
    await self.add_wheel(wheel, extras=set(), specifier="")
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 236, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 59, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 141, in add_requirement_inner
    satisfied, ver = self.check_version_satisfied(req)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 86, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'fastapi<1.0,>=0.115.2', but fastapi==0.110.3 is already installed

    at new_error (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:9965)
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[302]:0x16dbfd
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[489]:0x177431
    at _PyEM_TrampolineCall_JS (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:125894)
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1134]:0x1c2eaf
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[3602]:0x2c7c0f
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[2167]:0x20a884
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1142]:0x1c359c
```

### System Info

```shell
Chrome Version 129.0.6668.101 (Official Build) (64-bit)
Windows 11
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by whitphx**
## Description

* Starlette was updated in https://github.com/gradio-app/gradio/pull/9712 but installing the pinned version causes an error on Lite. `requirements.txt` is fixed.
* Also deleted out-of-date package installations in `webworker/index.ts`.

Resolves #9721

### CODE REVIEW

File: js/wasm/src/webworker/index.ts [hunk 1]
```diff
@@ -80,15 +80,6 @@ async function initializeEnvironment(
 	updateProgress("Loading Gradio wheels");
 	await pyodide.loadPackage(["ssl", "setuptools"]);
 	await micropip.add_mock_package("ffmpy", "0.3.0");
-	await micropip.install.callKwargs(
-		[
-			"typing-extensions>=4.8.0", // Typing extensions needs to be installed first otherwise the versions from the pyodide lockfile is used which is incompatible with the latest fastapi.
```
Comment (whitphx) [inline js/wasm/src/webworker/index.ts:85]: `typing-extensions` bundled in Pyodide has been updated (https://github.com/pyodide/pyodide/pull/4428, https://github.com/pyodide/pyodide/pull/4712) so this line is no longer needed.

File: js/wasm/src/webworker/index.ts [hunk 2]
```diff
@@ -80,15 +80,6 @@ async function initializeEnvironment(
...
-			"markdown-it-py[linkify]~=2.2.0", // On 3rd June 2023, markdown-it-py 3.0.0 has been released. The `gradio` package depends on its `>=2.0.0` version so its 3.x will be resolved. However, it conflicts with `mdit-py-plugins`'s dependency `markdown-it-py >=1.0.0,<3.0.0` and micropip currently can't resolve it. So we explicitly install the compatible version of the library here.
```
Comment (whitphx) [inline js/wasm/src/webworker/index.ts:86]: Gradio no longer depends on `markdonw-it-py`: https://github.com/gradio-app/gradio/pull/5268

File: js/wasm/src/webworker/index.ts [hunk 3]
```diff
@@ -80,15 +80,6 @@ async function initializeEnvironment(
...
-			"anyio==3.*", // `fastapi` depends on `anyio>=3.4.0,<5` so its 4.* can be installed, but it conflicts with the anyio version `httpx` depends on, `==3.*`. Seems like micropip can't resolve it for now, so we explicitly install the compatible version of the library here.
```
Comment (whitphx) [inline js/wasm/src/webworker/index.ts:87]: https://github.com/fastapi/fastapi/pull/10194

File: js/wasm/src/webworker/index.ts [hunk 4]
```diff
@@ -80,15 +80,6 @@ async function initializeEnvironment(
...
-			"fastapi<0.111.0" // `fastapi==0.111.0` added `ujson` as a dependency, but it's not available on Pyodide yet.
```
Comment (whitphx) [inline js/wasm/src/webworker/index.ts:88]: `ujson` is an optional dependency of `fastapi` so installing the latest `fastapi` doesn't cause the error.

**Comment by abidlabs** [comment]
I believe this should close: https://github.com/gradio-app/gradio/issues/9721

**Comment by whitphx** [comment]
I think so.

**Comment by abidlabs** [comment]
Tested with:

```html
<html>
	<head>
        <script type="module" src="https://gradio-lite-previews.s3.amazonaws.com/89e551595ca71b6f8417de1e3c0465161c339962/dist/lite.js"></script>        
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
	</head>
	<body>
		<gradio-lite>
		import gradio as gr

		def greet(name):
			return "Hello, " + name + "!"

		gr.Interface(greet, "textbox", "textbox").launch()
		</gradio-lite>
	</body>
</html>
```

some of the styling was off, but I think that's because I was using the wrong lite css bundle? Otherwise, the app worked great so I think we can go ahead and merge this in

**Review by abidlabs — APPROVED** [review]
